### ISSUE TITLE
[$50] Default decoration still rounded when maximized or tiled

### ISSUE THREAD

**Issue by PwnicornDev** [elementary/stylesheet#73] opened 2017-02-14 02:06 UTC
I'm not sure if this is possible, but it would look better if they behaved like the titlebar.

**Comment by danrabbit** [comment] 2017-02-14 02:08
What kind of apps are you able to reproduce this issue with? I can't seem to reproduce it

**Comment by PwnicornDev** [comment] 2017-02-14 02:14
Whoa, that was fast :D
If I maximize Firefox or GIMP, the decorations are still rounded.

**Comment by danrabbit** [comment] 2017-02-15 01:46
![screenshot from 2017-02-14 17 45 31](https://cloud.githubusercontent.com/assets/7277719/22957497/6ba98c1e-f2dd-11e6-8d3e-35bcf73d7d6f.png)

![screenshot from 2017-02-14 17 46 14](https://cloud.githubusercontent.com/assets/7277719/22957503/81382af4-f2dd-11e6-9d56-12bb37272cf1.png)

I can't confirm that. Are you running the latest version of elementary OS with all your updates installed?

**Comment by PwnicornDev** [comment] 2017-02-15 05:09
It's best noticeable with a dark wallpaper and moving the maximized window on its own workspace. Also if there is a native app maximized behind one with default decoration, the rounded corners of the foreground app are nearly invisible (in fact, I think that's the case with both screenshots above, playing around with the contrast in GIMP makes it more visible).
![image](https://cloud.githubusercontent.com/assets/3987812/22961159/302c34ae-f344-11e6-9890-1a0e050aa1d2.png)
![image](https://cloud.githubusercontent.com/assets/3987812/22961258/ff781052-f344-11e6-9baa-8638a384b215.png)

**Comment by cassidyjames** [comment] 2017-02-15 19:55
I can confirm that there's some thing a little odd happening with rounded titlebars for legacy apps and the new decorations. A good wallpaper to test with is just plain black or the `Mr. Lee.jpg` background that we ship.

**Comment by cassidyjames** [comment] 2017-02-15 19:56
![screenshot from 2017-02-15 12 55 38](https://cloud.githubusercontent.com/assets/611168/22992825/14adcece-f37e-11e6-9a64-eaf235b2eb9a.png)

**Comment by cassidyjames** [comment] 2017-02-15 19:57
Versus GTK3 apps

![image](https://cloud.githubusercontent.com/assets/611168/22992892/47bc4f5c-f37e-11e6-9019-d7eb5895fe67.png)

**Comment by Defman21** [comment] 2017-02-15 20:00
Even GTK3 apps are rounded.

**Comment by cassidyjames** [comment] 2017-02-15 20:03
@Defman21 the outside corners of the display are masked by Gala; that's unrelated to this issue. The place to look specifically is the inside corners that meet at the middle of the display for tiled windows.

**Comment by Defman21** [comment] 2017-02-15 20:06
So this rounded thing isn't an issue?

![image](https://cloud.githubusercontent.com/assets/7100645/22993229/52404596-f3d3-11e6-8dcb-1c3095fe0026.png)

**Comment by cassidyjames** [comment] 2017-02-15 20:08
@Defman21 ah, I should have said headerbar instead of GTK3. I think any app using the default decorations (whether GTK2 or GTK3) will have the same issue.

**Comment by codygarver** [comment] 2017-03-24 08:00
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/42001151-default-decoration-still-rounded-when-maximized-or-tiled).

**Comment by h4ndshake** [comment] 2017-04-07 06:18
@cassidyjames So, are you saying that Vala apps have a masked (probably) 3px border-radius, while GTK{2, 3} have mixed (no, or 5px (probably) border-radius?

If this is the case, what about unifying it's looks by adding a 3px border-radius for both GTK 2 and 3 apps?

**Comment by danrabbit** [comment] 2017-09-17 19:32
I'm gonna close this since every window decoration now always has rounded corners whether maximized or not

**Closed by danrabbit** 2017-09-17 19:32 UTC
Labels: Bounty, Status: Confirmed

**Comment by PwnicornDev** [comment] 2017-09-20 20:44
Tiled apps are still square and the issue affects them the same way. Not sure how this could be handled, making apps always round would be consistent, but square corners look nicer in a tiled setup. 

(Personally I also think fullscreen apps look nicer when squared, since you can see bits of the wallpaper through the corners, which looks unclean imo, but that's getting off topic.)

**Comment by danrabbit** [comment] 2017-09-20 20:45
Nothing can really be done about tiled since we don't get information from the window manager about which corners are tiled.

You won't see wallpaper behind maximized apps because we draw black behind them
