### ISSUE TITLE
GTK+ > 3.18 not supported

### ISSUE THREAD

**Issue by decathorpe** [elementary/stylesheet#44] opened 2016-11-07 20:36 UTC
GTK 3.20 has been released on 2016-03-21, and that release broke the elementary theme. The latest stable ubuntu (yakkety+) and fedora (24+) releases provide only GTK+ from the 3.20 series (or newer), and thus the elementary theme is not supported / working correctly on those leading linux distributions.

Providing support for the theming API of GTK 3.20 / 3.22 looks like a win to me, since GTK 3.22 will be maintained as the last stable GTK3 branch for about 3 years (https://blog.gtk.org/2016/09/01/versioning-and-long-term-stability-promise-in-gtk/).

**Comment by danrabbit** [comment] 2016-11-07 23:05
Gtk >=3.20 support is planned (and even in progress), but it won't land until there is a release of elementary OS that makes use of Gtk >=3.20

**Comment by gwutz** [comment] 2017-01-23 11:37
Ok i started to work on this. I forked the existing repo and created a branch (fix3.22) to get this working at a minimum level. Is it okay to document every problem here with screenshots or should i avoid this. I just need a platform where i can get suggestions about intended behaviour and style and current behaviour and style. So we can work every disfunctional detail step by step until we get an working theme for >3.18. For example this is the current scrollbar. It isnt there at all and its nearly impossible to click it - 1px grab. 

![bildschirmfoto von 2017-01-23 12 28 10](https://cloud.githubusercontent.com/assets/373597/22202257/956d858c-e167-11e6-8b16-63e0b9b19b09.png)

Relevant code is:
```
/*************
* Scrollbars *
*************/

scrollbar,
.scrollbar {
    background-color: transparent;
    transition: all 600ms ease-out;
    -GtkRange-slider-width: 5;
    -GtkRange-stepper-spacing: 0;
    -GtkRange-trough-border: 1;
    -GtkRange-trough-under-steppers: 1;
    -GtkScrollbar-has-backward-stepper: false;
    -GtkScrollbar-has-forward-stepper: false;
    -GtkScrollbar-min-slider-length: 30;
}

scrollbar:hover,
.scrollbar:hover {
    transition: all 200ms ease-in-out;
    -GtkRange-slider-width: 10;
}

scrollbar button,
.scrollbar.button,
.scrollbar.button:active,
.scrollbar.button:active:hover,
.scrollbar.button:disabled,
.scrollbar.button:hover:backdrop,
.scrollbar.button:active:hover:backdrop {
    border: none;
    background-image: none;
    background-color: transparent;
}

scrollbar.overlay-indicator slider,
.slider {
    border: 1px solid alpha (@bg_highlight_color, 0.25);
    background-color: alpha (@text_color, 0.6);
    border-radius: 10px;
}

scrollbar.overlay-indicator slider:hover,
.slider:hover {
    border-radius: 20px;
}

scrollbar trough,
.scrollbar.trough {
    padding: 0;
}

scrollbar.overlay-indicator trough,
.scrollbar.overlay-indicator.trough {
    background-color: transparent;
}

scrollbar.overlay-indicator trough:hover,
.scrollbar.overlay-indicator.trough:hover {
    background-color: alpha (#000, 0.1);
}

scrollbar:hover trough,
.scrollbar:hover.trough {
    background-color: transparent;
    border-radius: 0;
}

.trough {
    background-color: @base_color;
}
```

I need to know how the intended behaviour is for the scrollbar to fix it. @danrabbit can you help out with that?

**Comment by danrabbit** [comment] 2017-01-23 18:34
It would probably be better to open a new issue report for each individual issue and submit individual PRs to address each individual issue. Commenting on this report is just going to end up with a huge mess and we won't be able to track progress in any meaningful way

**Comment by danrabbit** [comment] 2017-01-23 20:15
I'm going to close this issue report since we've start to track issues individually.

**Closed by danrabbit** 2017-01-23 20:15 UTC
Labels: Priority: Medium, Status: Blocked
