### ISSUE TITLE
Need to overwrite link_color into Gramps application

### ISSUE THREAD

**Issue by romjerome** [elementary/stylesheet#460] opened 2018-12-22 19:26 UTC
I get a problem with Elementary Gtk theme (under elementary OS 0.3.2) and gramps 5.0.1 application : I cannot see url using white color on a white background.

A bug report has been filled on gramps bug tracker:
https://gramps-project.org/bugs/view.php?id=10715

How can I overwrite link_color set on Elementary Gtk theme?

best regards,

**Comment by danrabbit** [comment] 2018-12-22 19:39
Closing as a duplicate of https://github.com/elementary/stylesheet/issues/436

elementary OS 0.3.2 is a very old and out of date release. Users should upgrade to 5.0

**Closed by danrabbit** 2018-12-22 19:39 UTC

**Comment by ztefn** [comment] 2018-12-23 17:13
Yes, that's right, you should upgrade! [Oh, wait...](https://github.com/elementary/appcenter/issues/3)
