### ISSUE TITLE
menu bar error Elementary Os ??? need help pleas

### ISSUE THREAD

**Issue by fayadGui** [elementary/stylesheet#583] opened 2020-01-27 04:27 UTC
![Captura de tela de 2020-01-27 01 26 10](https://user-images.githubusercontent.com/60334933/73150246-294dcc00-40a4-11ea-89c0-7b1c811b4448.png)

**Comment by danrabbit** [comment] 2020-01-27 16:11
Closing as a duplicate of https://github.com/elementary/triage/issues/9

**Closed by danrabbit** 2020-01-27 16:11 UTC
