### ISSUE TITLE
Strange windows appearance

### ISSUE THREAD

**Issue by t3mnikov** [elementary/stylesheet#467] opened 2019-01-13 21:52 UTC
![image](https://user-images.githubusercontent.com/11781965/51091058-4e6fe500-1796-11e9-8115-cc45194c5472.png)
![image](https://user-images.githubusercontent.com/11781965/51091065-562f8980-1796-11e9-8258-4ee93ea34c6f.png)
![image](https://user-images.githubusercontent.com/11781965/51091066-5c256a80-1796-11e9-80f1-e37f105504e0.png)

On the first two images Smartgit latest version 18.2.3 #13220. On the third image of PlayOnLinux 4.2.12. I ask you to correct this behavior of windows

**Comment by danrabbit** [comment] 2019-01-13 23:08
Closing as a duplicate of https://github.com/elementary/gala/issues/244

**Closed by danrabbit** 2019-01-13 23:08 UTC

**Comment by t3mnikov** [comment] 2019-01-14 14:11
I'm sorry, but that doesn't solve the problem in Smartgit. 
I run app like this 'env GTK_CSD=0 "/usr/share/smartgit/bin/smartgit.sh" %u'
Look at this image.
![image](https://user-images.githubusercontent.com/11781965/51117509-13fe5a80-181f-11e9-99f5-d649a0d5351b.png)
Please check with yourself
