### ISSUE TITLE
Add a weather applet to the Date and Time settings at the top bar

### ISSUE THREAD

**Issue by diddy-boy** [elementary/stylesheet#1048] opened 2021-06-03 09:28 UTC
## Problem

An idea from Ubuntu Budgie but would it be easy to add a weather applet to the top bar alongside the Date and Time ?

There are a few apps on Flatpak that allow the user to install a weather app but it involves the user running up the app to see the weather forecast.

Daniel, you could add your Nimbus weather app into the panel ?

## Proposal

add an app that the user can set their own location (or use the location service) to download the weahter information and display along side the user configurable units for temperature and wind units etc

**Comment by danrabbit** [comment] 2021-06-03 16:17
Closing as a duplicate of https://github.com/elementary/wingpanel-indicator-datetime/issues/255

**Closed by danrabbit** 2021-06-03 16:17 UTC
