### ISSUE TITLE
Add margin between labels and icons on System Settings

### ISSUE THREAD

**Issue by eumunhoz** [elementary/stylesheet#613] opened 2020-04-27 03:10 UTC
There is no gap set between labels and the icons on System Settings. Although it looks like there is, it's actually the line-height of the label.

![Captura de tela de 2020-04-26 23-53-28](https://user-images.githubusercontent.com/24512504/80329921-1d47e680-881a-11ea-8a70-d32ef2f794a0.png)

![Captura de tela de 2020-04-26 23-54-39](https://user-images.githubusercontent.com/24512504/80329932-289b1200-881a-11ea-89cb-0afc3a261bbb.png)

This is how it looks right now:

![Captura de tela de 2020-04-27 00-05-30](https://user-images.githubusercontent.com/24512504/80330301-30a78180-881b-11ea-9fef-7a03e15aad67.png)

I suggest adding a gap between then to increase legibility. Something like this:

![Captura de tela de 2020-04-27 00-05-48](https://user-images.githubusercontent.com/24512504/80330312-38672600-881b-11ea-9a93-c2affe60cc16.png)

**Comment by alainm23** [comment] 2020-04-27 04:14
A good observation but the correct place to open it is here:
https://github.com/elementary/switchboard

**Comment by eumunhoz** [comment] 2020-04-27 13:51
Thanks! I'll create an issue there

**Comment by cassidyjames** [comment] 2020-04-27 16:59
Duplicate of https://github.com/elementary/switchboard/issues/154

**Closed** 2020-04-27 16:59 UTC
Labels: Status: Duplicate
