### ISSUE TITLE
'Open' indicators of dock still red

### ISSUE THREAD

**Issue by kdwk** [elementary/stylesheet#1071] opened 2021-08-11 07:50 UTC
## What Happened

![Screenshot from 2021-08-11 15-47-54](https://user-images.githubusercontent.com/39268094/128990548-a0925dd9-9823-43e3-b6ab-13e15ce6dfde.png)

A while back I remember an issue was closed because the indicators were fixed and made to be symbolic, but I couldn't see any change. On Odin stable I'm still seeing the red indicators

## Expected Behavior

The indicators become symbolic (white when dark mode is active, deep grey when light mode is active)

## Steps to Reproduce

1. Open an app
2. Observe the indicator
3.

**Comment by cassidyjames** [comment] 2021-08-11 15:53
Thanks for reporting! It looks like this is a duplicate of https://github.com/elementary/dock/issues/100

**Closed by cassidyjames** 2021-08-11 15:53 UTC
