### ISSUE TITLE
Strange behavior of the panel with some wallpapers

### ISSUE THREAD

**Issue by michalzkosmosu** [elementary/stylesheet#558] opened 2019-10-25 12:10 UTC
When I start my laptop, the panel behaves as you can see on the attached png. When I change my wallpaper to another one and then restore the original one again, everything goes back to normal. But after restarting, I have to fix it again.
![wrong](https://user-images.githubusercontent.com/57003201/67570116-e42a9e80-f730-11e9-9771-8aee5dd2e3bc.png)
![good](https://user-images.githubusercontent.com/57003201/67570133-f278ba80-f730-11e9-9ff5-e43404a64cab.png)

**Comment by cassidyjames** [comment] 2019-10-25 15:30
Thanks for reporting! However, this looks like a duplicate of https://github.com/elementary/gala/issues/613

**Closed by cassidyjames** 2019-10-25 15:30 UTC
