### ISSUE TITLE
Maximise Button Padding

### ISSUE THREAD

**Issue by Bearddyy** [elementary/stylesheet#891] opened 2020-12-01 11:08 UTC
## Bug Report
The Padding is too large between the Maximise button and the previous app specific icons in the menu bar.
It is most visible on the Elementary Terminal however once you notice it you can see it on the calendar too.
![image](https://user-images.githubusercontent.com/11067495/100731242-0aeee600-33c3-11eb-81bc-0832f7dbec89.png)
![image](https://user-images.githubusercontent.com/11067495/100730212-ada66500-33c1-11eb-9fde-6ef44e791aed.png)

Its also somewhat noticeable in Code and the Calculator however less so due to the layout of the other buttons
![image](https://user-images.githubusercontent.com/11067495/100730627-30c7bb00-33c2-11eb-8a77-ee70e28e9dfb.png)
![image](https://user-images.githubusercontent.com/11067495/100733022-7d60c580-33c5-11eb-8857-00b22140fa06.png)

Changing the layout using tweaks seems to keep the same effect too.

![image](https://user-images.githubusercontent.com/11067495/100731745-b5ff9f80-33c3-11eb-9d5c-65ccc36e2fe5.png)
![image](https://user-images.githubusercontent.com/11067495/100731823-cf085080-33c3-11eb-9644-69cbf501baeb.png)

This leads me to believe its some kind of padding done in GTK? 
I'm not very familiar with GTK etc so couldnt find any definitive padding in this repo to suggest a change and try it out.  

I had a look around the Elementary repos and this one seemed to be the most likely candidate for the bug, please correct me if I'm wrong.
I have made this a Bug report rather than a feature request as I don't think its intended design but feel free to re-categorise

## Expected Behavior
The buttons should have a constant amount of padding from one another.
I would expect the spacing between the maximise/minimise button to the Settings icon to be the same as the distance between the Settings icon and the Search icon

## Steps to Reproduce
Simply open the Terminal in Elementary.  
I don't think my resolution/aspect ratio is causing this as the spacing is constant regardless of resizing the window
and the problem is also present on the Elementary Terminal's github readme image:
![image](https://raw.githubusercontent.com/elementary/terminal/master/data/screenshot.png)

## Platform Information
![image](https://user-images.githubusercontent.com/11067495/100731008-bb101f00-33c2-11eb-84a3-43e89c320d75.png)

**Comment by danrabbit** [comment] 2020-12-02 19:57
This is intentional to separate window controls from tool items

Closing as "Design conflict" since this is an intentional design choice and not a bug

**Closed by danrabbit** 2020-12-02 19:57 UTC
