### ISSUE TITLE
Playonlinux bug

### ISSUE THREAD

**Issue by giovannicaligaris** [elementary/stylesheet#359] opened 2018-07-11 12:20 UTC
Running a fresh install of Juno. I am not sure if this is an issue with PlayonLinux or a theme issue with eOS.

![screenshot from 2018-07-11 08 18 57](https://user-images.githubusercontent.com/26255347/42570819-2073380a-84e3-11e8-99ec-6202c61d0c8f.png)

**Comment by BaptisteGelez** [comment] 2018-07-11 12:30
Duplicate of #348

**Closed** 2018-07-11 16:02 UTC
