### ISSUE TITLE
Back buttons are blurry

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#272] opened 2018-02-15 22:13 UTC
I don't know how long this has been an issue, but on my fresh Juno install, I noticed all back buttons appear to be a bit blurry.
![screenshot from 2018-02-15 15 12 11](https://user-images.githubusercontent.com/611168/36283761-b168e880-1262-11e8-8754-d53da5f32d1a.png)
![screenshot from 2018-02-15 15 11 34](https://user-images.githubusercontent.com/611168/36283763-b2744616-1262-11e8-89e4-62477853a0e3.png)
![screenshot from 2018-02-15 15 11 22](https://user-images.githubusercontent.com/611168/36283769-b38a7818-1262-11e8-9b1f-75d643e6974c.png)
![image](https://user-images.githubusercontent.com/611168/36283863-172f0c8a-1263-11e8-8ec3-92337c2dd988.png)

**Comment by cassidyjames** [comment] 2018-02-15 22:17
I'm on Juno on HiDPI, fwiw

**Comment by danrabbit** [comment] 2018-02-25 17:13
This seems to be an issue with all SVG assets

**Comment by danrabbit** [comment] 2018-02-27 18:18
I'm beginning to think this might be a regression in Gtk+. It affects the slider assets in Adwaita as well :(

![screenshot from 2018-02-27 10 16 38](https://user-images.githubusercontent.com/7277719/36746585-8b1e5d38-1ba7-11e8-9c5e-6c16322c3e80.png)

**Comment by danrabbit** [comment] 2018-03-21 18:38
Closing because this seems to be a bug in Gtk+ only affecting HiDPI. Reported here: https://gitlab.gnome.org/GNOME/gtk/issues/118

**Closed by danrabbit** 2018-03-21 18:38 UTC
Labels: Status: Confirmed
