### ISSUE TITLE
Top panel goes black with fullscreen app on secondary monitor

### ISSUE THREAD

**Issue by pbirkbeck** [elementary/stylesheet#350] opened 2018-07-05 21:01 UTC
If I make an application full screen on my primary monitor then the top panel is transparent as expected. If I make an application full screen on second monitor then panel goes black and looks ugly.

**Comment by Astro-City** [comment] 2018-07-06 21:16
Hi.

Are you talking about when you bring a window forward when another one is in fullscreen? Like opening a link on a new window on your browser?

I don't know how to fix the issue, but i think the normal behavior should be the "ugly one". Don't you think that turning the panel black when something is in the fullscreen mode is more functional since the panel text doesn't get "camouflaged" on the fullscreen background?

Thanks.

**Comment by danrabbit** [comment] 2018-07-07 10:42
The stylesheet doesn't really control this. It only describes the styles associated with classes, but the panel is what is responsible for adding and removing those classes.

Closing as "Out of scope" for this repo because the issue is unable to be solved here. You may want to open an issue at https://github.com/elementary/wingpanel/issues

**Closed by danrabbit** 2018-07-07 10:42 UTC
