### ISSUE TITLE
Minecraft launcher abnormal

### ISSUE THREAD

**Issue by inksalt** [elementary/stylesheet#571] opened 2019-12-21 10:08 UTC
![image](https://user-images.githubusercontent.com/10728028/71306546-aa1e0600-241c-11ea-9d5e-f00bf2cd8679.png)

**Comment by ryonakano** [comment] 2019-12-21 10:30
Thank you for your report, but I guess this is a duplicate of elementary/gala#244

**Comment by cassidyjames** [comment] 2019-12-23 17:53
@inksalt how have you installed Minecraft so someone can try to reproduce this?

**Closed by cassidyjames** 2019-12-23 17:53 UTC
