### ISSUE TITLE
Top panel turns black when windows maximized

### ISSUE THREAD

**Issue by send2r** [elementary/stylesheet#1013] opened 2021-05-04 19:08 UTC
## What Happened
Running the beta version
When I maximize a window, the top panel turns black and a 2px gap appears on top.

## Expected Behavior
Top panel retains its translucency

## Steps to Reproduce
1. Launch files
2. maximize the window
3. Top panel turns black
![Screenshot from 2021-05-04 19 08 08@2x](https://user-images.githubusercontent.com/13864239/117056680-1c3e7480-ad0c-11eb-9f4f-25a37e9e2931.png)

**Comment by danrabbit** [comment] 2021-05-04 19:11
It's intentional for the panel to become opaque when windows are maximized. The other issue is a duplicate of https://github.com/elementary/wingpanel/issues/69

Please try to keep issue reports to one issue at a time :)

**Closed by danrabbit** 2021-05-04 19:11 UTC
