### ISSUE TITLE
Fix Button Colors in Dark Applications

### ISSUE THREAD

**Issue by btd1337** [elementary/stylesheet#204] opened 2017-09-17 16:00 UTC
Is it possible to correct the button colors, when mouse is hover, in dark applications?

Reproduction of the problem:

See the 'Cancel' button

Normal

![screenshot from 2017-09-17 12-33-31](https://user-images.githubusercontent.com/11943860/30522526-ced1e23c-9ba7-11e7-81d0-ed89d3316e6f.png)

and now, when mouse is over:

![screenshot from 2017-09-17 12-33-33](https://user-images.githubusercontent.com/11943860/30522530-ec068ad8-9ba7-11e7-92a4-ce869311d976.png)

You can't see the button text.

**Comment by danrabbit** [comment] 2017-09-17 22:02
Closing as a duplicate of #205

**Closed by danrabbit** 2017-09-17 22:02 UTC
