### ISSUE TITLE
It's mostly impossible to see which tab is active using dark theme

### ISSUE THREAD

**Issue by kkinder** [elementary/stylesheet#463] opened 2019-01-04 20:57 UTC
Here's a quick screenshot.

![image](https://user-images.githubusercontent.com/1115018/50710592-f700a500-1030-11e9-9322-0e081e9be644.png)

I defy you to tell me, within 1 second and reliably, which tab is actually active. There needs to be *something* to increase the contrast between the active/selected tab and the others.

**Comment by danrabbit** [comment] 2020-04-17 17:46
I'm gonna close this as a duplicate of #360

**Closed by danrabbit** 2020-04-17 17:46 UTC

**Comment by cassidyjames** [comment] 2020-04-19 15:19
@danrabbit I can see it going either way, but to my eye the dark tabs are much harder to distinguish due to lower contrast between the surface and the stroke. With light tabs, there's more contrast and they feel much easier to pick out to me. 

However, a solution may involve tweaking the design for tabs altogether.
