### ISSUE TITLE
Provide a tarball release

### ISSUE THREAD

**Issue by bilelmoussaoui** [elementary/stylesheet#418] opened 2018-10-04 07:32 UTC
Currently, the latest release was a year ago. It would be really nice to have even beta releases here on Github. The same thing goes for the Gtk theme. 

Packaging those kinds of stuff using the latest master commit isn't the best idea at all... I had this issue when I tried to create a Juno BaseApp for Flatpaked elementary apps, see here https://github.com/flathub/flathub/pull/658.

**Comment by codygarver** [comment] 2018-10-04 09:52
Duplicate of #391

**Closed by codygarver** 2018-10-04 09:52 UTC
