### ISSUE TITLE
GNOME apps have "Maximize" button at an incorrect position

### ISSUE THREAD

**Issue by uncertainquark** [elementary/stylesheet#354] opened 2018-07-08 15:52 UTC
All GNOME apps have the "maximize" button to the left of the "GNOME app menu". Example screenshots below.
![01-gnome-nautilus](https://user-images.githubusercontent.com/22585732/42421545-ed8142a6-82f4-11e8-8b5b-52131690ecef.png)
![02-gnome-terminal](https://user-images.githubusercontent.com/22585732/42421546-edb64a8c-82f4-11e8-863d-a737e3a61cb9.png)
![04-gnome-calculator](https://user-images.githubusercontent.com/22585732/42421548-ee3da3ce-82f4-11e8-9471-17139079315d.png)
![05-gnome-monitor](https://user-images.githubusercontent.com/22585732/42421549-ee987da8-82f4-11e8-8e1b-7cd71990f11a.png)
![06-gnome-disks](https://user-images.githubusercontent.com/22585732/42421550-eecf562a-82f4-11e8-97dd-9428fbe84338.png)

**Comment by snwh** [comment] 2018-07-08 15:55
This isn't within the scope of the stylesheet, so closing for being out-of-scope.

That said, window control positioning (which includes the menu) is something that you can change within a tweak-tool.

**Closed by snwh** 2018-07-08 15:55 UTC

**Comment by uncertainquark** [comment] 2018-07-08 15:58
Under which project should I report the bug then? Can you please point me towards it?

**Comment by surajmandalcell** [comment] 2018-07-08 17:02
He is saying its not a bug its how it is supposed to be but if you don't like it you can change it using tweak tool (gnome tweak tool or elementary tweaks).

**Comment by snwh** [comment] 2018-07-08 22:45
Right, it isn't a bug. GNOME apps have the AppMenu and when used outside of GNOME shell the menu appears in the headerbar. 

The relevant gsettings key in dconf-editor is `/org/gnome/desktop/wm/preferences/ button-layout` you can move or hide the appmenu as you like.
