### ISSUE TITLE
Wingpanel.Widgets.Switch label uses power symbols

### ISSUE THREAD

**Issue by worldofpeace** [elementary/stylesheet#556] opened 2019-06-12 02:52 UTC
##### Current appearance in network indicator
![Screenshot from 2019-06-11 22 35 32](https://user-images.githubusercontent.com/28888242/59319654-832a8e80-8c99-11e9-8890-e25f56f2a192.png) (on state)

![Screenshot from 2019-06-11 22 42 13](https://user-images.githubusercontent.com/28888242/59319946-7f4b3c00-8c9a-11e9-8730-6d55ae96ce7e.png) (off state)

There's been recent changes to `Gtk.Switch` that probably have influenced this

* https://gitlab.gnome.org/GNOME/gtk/commit/45ee476e36814810f0f62fcdbf7401ee31478a07
* https://gitlab.gnome.org/GNOME/gtk/commit/796e884c3f90598f352f9c7886ceb671f257c134
* https://gitlab.gnome.org/GNOME/gtk/commit/ed39721aa7435860f46da69998cf6cac4ae7e735
* https://gitlab.gnome.org/GNOME/gtk/commit/6a4ce55a69c5ecbbf06bc905ac0bfdd04f64bb66
* https://gitlab.gnome.org/GNOME/gtk/commit/75a4ae2aba8bbd97689549b735ee149473b9e7eb

**Comment by danrabbit** [comment] 2019-10-14 21:24
@worldofpeace I see this in the Epiphany flatpak, but not in Builder. Can you reproduce this will the latest elementary stylesheet? I wonder if this was a problem in an older version?

**Comment by worldofpeace** [comment] 2019-10-14 21:40
@danrabbit Produced in a NixOS VM with the stylesheet from master 
![Screenshot from 2019-10-14 17-37-26](https://user-images.githubusercontent.com/28888242/66784755-584f8180-eea9-11e9-899e-bd1212be42eb.png)

This was opened in Wingpanel because it only applied to Wingpanel.Widgets.Switch.
So for example, all the switches used in switchboard plugs appear without those symbols.
While Wingpanel.Widgets.Switch is always appeared like this.

**Comment by danrabbit** [comment] 2019-10-14 23:47
Hm, that is odd. There are no special properties set there

**Comment by cassidyjames** [comment] 2019-10-15 03:06
This is also visible in the preferences for the Epiphany Tech Preview Flatpak.

**Comment by Exalm** [comment] 2019-10-15 04:11
You can switch to Adwaita or HighContrast and check if it shows | and O or ON and OFF in both.

Before GTK 3.24 it used ON/OFF for en_US and |, O as fallback. So it might be different locale in wingpanel and switchboard.

As for Epiphany flatpak, it uses a newer GTK than host, so the stylesheet needs an update (or maybe it's already updated and the one on Flathub is just old?). It's apparent from how widget factory looks like:

![Screenshot from 2019-10-15 09-09-44](https://user-images.githubusercontent.com/1510457/66799686-a2645180-ef01-11e9-933c-888e8db55670.png)

Adwaita does it somehow now, so it's possible to hide them.

**Comment by cassidyjames** [comment] 2019-10-30 02:58
Yaru hides it with a simple `switch { font-size: 0 }`, I'd assume Adwaita is similar.

https://github.com/ubuntu/yaru/blob/2d2cf90a2675a72545ca1781f8143c8f9c285ae5/gtk/src/default/gtk-3.20/_tweaks.scss#L181

**Comment by Exalm** [comment] 2019-10-30 18:28
https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/theme/Adwaita/_common.scss#L2824 :)

**Comment by Exalm** [comment] 2019-10-30 18:29
so `switch image { color: transparent; }` if without scss.

**Comment by worldofpeace** [comment] 2019-11-26 14:03
I've built and installed stylesheet from git master and still have this issue in NixOS
![Screenshot from 2019-11-26 09-01-17](https://user-images.githubusercontent.com/28888242/69639888-6efe0200-102b-11ea-9c59-7ff97532f54c.png).

**Comment by danrabbit** [comment] 2020-03-03 17:25
Yeah I can confirm the issue persist in focal

**Comment by danrabbit** [comment] 2020-05-06 19:45
Fixed in greenfield

**Comment by danrabbit** [comment] 2020-05-11 18:39
Closing since this is fixed in Greenfield

**Closed by danrabbit** 2020-05-11 18:39 UTC
Labels: Status: Confirmed
