### ISSUE TITLE
Tabs' styles are inconsistent across the system 

### ISSUE THREAD

**Issue by dcominottim** [elementary/stylesheet#211] opened 2017-10-10 01:18 UTC
For instance, let us compare the tabs from Files to the tabs from Network Settings -> Advanced Settings. In Files, the tabs seem more modern and with correct borders (a very thin line at the top and a thin shadow at the bottom); but in Network Settings -> Advanced Settings there is no top border (it looks like a part of the tab is missing) and there is a **very** thick line at the bottom, which seems way off.

![tabs](https://user-images.githubusercontent.com/4914233/31365164-ca767fc8-ad3f-11e7-8afb-305432539abe.jpg)

**Comment by harveycabaguio** [comment] 2017-10-11 02:05
I believe this has nothing to do with the theme itself but with how the advanced network settings is designed. The double line at the bottom is caused by the tab area drawing its own border, and the top of the tab doesn't have a top border by design as the headerbar is expected to be above it.

**Comment by dcominottim** [comment] 2017-10-11 17:50
@harveycabaguio the design of Advanced Networking Settings is used in other parts of the system, I think. I will confirm and post screenshots if applicable tonight.

**Comment by dcominottim** [comment] 2017-10-12 01:09
The same happens for Epiphany. I think the issue applies to all non-native apps that use tabs:

![epiphany](https://user-images.githubusercontent.com/4914233/31474384-cc41ff5c-aed0-11e7-8311-6639c646bdf5.PNG)

**Comment by harveycabaguio** [comment] 2017-10-12 02:18
These instances should be using the [static notebook](https://elementary.io/docs/human-interface-guidelines#static-notebook) or some other form of navigation, not the dynamic notebook that its using right now, so this isn't a theme issue.

They will have to be filed against the [networking plug](https://github.com/elementary/switchboard-plug-networking/issues) and [elementary OS](https://bugs.launchpad.net/elementaryos) (since afaik the epiphany UI fork doesn't have its own project). If you find any more like these please file them against that project!

**Comment by dcominottim** [comment] 2017-10-12 14:26
Are they actually using a dynamic notebook? They seem reasonably different from the screenshot of the documentation you linked. 

What about other 3rd party applications that might use the dynamic notebook component for whatever reason? Will their theme remain "broken" only in eOS, just because they don't follow the guidelines for native eOS apps?

Honestly, if I understood your reply correctly, I don't think this solution is reasonable at all. I can open bugs against the Networking Plug and Epiphany if the eOS teams is responsible for them, sure; but if the solution leaves everything up to application developers and 3rd party applications will look fine in other themes and "broken" just in eOS, then by all means I think it is a theme issue from eOS's side.

**Comment by danrabbit** [comment] 2017-10-12 16:46
The real solution is for these apps to use the right widgets, but it does look like with enough deep dark magic we can specifically target notebooks used in this way:

![screenshot from 2017-10-12 09 44 38](https://user-images.githubusercontent.com/7277719/31508164-145810a4-af32-11e7-93a8-4679e7f8fa18.png)

**Comment by dcominottim** [comment] 2017-10-12 16:49
@danrabbit that seems incredibly better.

**Comment by dcominottim** [comment] 2018-05-16 00:06
@danrabbit please give this some love before Juno is released!

**Comment by danrabbit** [comment] 2021-05-11 21:34
Tabs have been redesigned so I'm going to close this as fixed

**Closed by danrabbit** 2021-05-11 21:34 UTC
