### ISSUE TITLE
Locked Down Desktop

### ISSUE THREAD

**Issue by terrystech** [elementary/stylesheet#785] opened 2020-08-13 18:11 UTC
I have noticed your developer postings about "keeping the desktop clean and clutter free" but if you truly want users to adopt and recommend this distro you need to give us, the end user, the option.  Otherwise you are just like the Big Two forcing your whims and will on others without choice.  The OS is amazing if you would just release a tweak page for it that allows the end users to customize the look and feel, including the ability to create desktop shortcuts to applications, files, internet sites, etc.

**Comment by danrabbit** [comment] 2020-08-13 18:17
Nothing is "locked down". You're totally free to install any app you would like that might draw things over the background. In fact there's a popular one in AppCenter called "Desktop Folder" that you can check out here: https://appcenter.elementary.io/com.github.spheras.desktopfolder/

Either way, this doesn't have anything to do with the stylesheet, so I'm gonna close as "Out of Scope"

**Closed by danrabbit** 2020-08-13 18:17 UTC

**Comment by terrystech** [comment] 2020-08-13 20:51
Wow man that was likely the most aggressive tech support response I've ever 
encountered.  Makes me sorry I contributed money toward this project.

**Comment by cassidyjames** [comment] 2020-08-25 19:19
@terrystech I am not sure what is considered aggressive about Dan's response, but I'm sorry if it came off that way. To clarify, GitHub is not tech support, but is where we triage and address issues and features for our software. As Dan mentioned, this repository is for the system-wide stylesheet, which doesn't have anything to do with the desktop itself—so your issue here is considered "out of scope", which is a way we triage the thousands of opened issues in order to be able to keep them organized and address them if needed.

Regarding the desktop being "locked down," by design elementary OS just does not put anything on top of your desktop wallpaper. But that functionality _can_ be added by users via third-party apps like [Desktop Folder](https://appcenter.elementary.io/com.github.spheras.desktopfolder/) if they so choose. It's not a matter of "just releasing a tweak page," but it would require elementary developers to divert time and resources from the rest of the OS to design and develop a feature that explicitly does not align with our design goals—all just to disable it by default. A big part of what defines elementary OS is our opinionated design approach without excessive configuration. We also believe that anyone has the choice to use elementary OS or not! If it's not for you, that's completely fine; there are tons of other great Linux-based operating systems out there that may better cater to your wishes.
