### ISSUE TITLE
Panel is movable with two finger drag on touch screen laptop 

### ISSUE THREAD

**Issue by ariebh** [elementary/stylesheet#517] opened 2019-06-12 10:23 UTC
![Screenshot from 2019-06-12 22 19 16@2x](https://user-images.githubusercontent.com/48895734/59343778-b84de400-8d60-11e9-943b-fda04c462b8c.png)

**Comment by tintou** [comment] 2019-06-12 10:25
duplicate of https://github.com/elementary/wingpanel/issues/169

**Closed by tintou** 2019-06-12 10:25 UTC
