### ISSUE TITLE
Firefox Big Black Shadow around pop-up

### ISSUE THREAD

**Issue by luki9100** [elementary/stylesheet#845] opened 2020-10-06 06:53 UTC
I have a big black shadow around my firefox pop ups. As far as I could read on the internet, this is an issue with the GTK stylesheet in elementary. Here is an example:
![Screenshot from 2020-10-06 08 52 09](https://user-images.githubusercontent.com/26790273/95168218-45684800-07b1-11eb-959f-3888db1d17fc.png)

**Comment by worldofpeace** [comment] 2020-10-27 07:27
Hi, I'm not sure this is an issue with our stylesheet. I actually tested this in NixOS and could only reproduce if I changed gala to use mutter 3.36. I believe this to then be a mutter issue

**Comment by worldofpeace** [comment] 2020-10-27 07:39
I've opened a bug at gala ^ with some more details. Hopefully we can find the cause, but a lot of times in mutter weird stuff happens with firefox and I expect similar for gala

**Comment by danrabbit** [comment] 2020-10-28 23:54
According to the information provided at the other issue report, it seems that this cannot be reproduced with the latest elementary stylesheet on Ubuntu 20.04, and it can be reproduced with Adwaita, so it seems like it's a Gala issue.

Closing as "Out of scope" for the stylesheet

**Closed by danrabbit** 2020-10-28 23:54 UTC
