### ISSUE TITLE
Problems with some icons on elementary OS 5.0 Juno

### ISSUE THREAD

**Issue by OlioDiPalmas** [elementary/stylesheet#426] opened 2018-10-19 17:23 UTC
Some icons, like "Multitasking View" (Vista multitasking) and "More" (Altro; which is in System Settings > Notifications) **don't display correctly** if the system language is set to **Italian**. You can fix this problem easily by changing the language to English, but it isn't the best solution if you prefer Italian.

The problem is certainly due to a translation error in the .desktop files, where the icon name is translated (for example: Icon[it]=vista-multitasking) but for some odd reason the string isn't linked to the original icon, so it shows a generic icon (🚫 or ⚙️). Another way you can fix this without changing the system language is to change the icon name for the Italian language with the English one (from Icon[it]=vista-multitasking to Icon[it]=multitasking-view) in the .desktop file in /usr/share/applications

![schermata del 2018-10-19 13 05 49 2x](https://user-images.githubusercontent.com/29050575/47233748-ffebbe00-d3d3-11e8-8e4d-cda0b87c27ae.png)
![schermata del 2018-10-19 13 06 02 2x](https://user-images.githubusercontent.com/29050575/47233749-ffebbe00-d3d3-11e8-88c5-2c5b3480ae9e.png)

**Comment by peteruithoven** [comment] 2018-10-19 17:30
I'm afraid this a duplicate of: https://github.com/elementary/gala/issues/358

**Closed** 2018-10-19 17:32 UTC
Labels: Status: Duplicate
