### ISSUE TITLE
Thunderbird - Text Selection doesn't work on elementary OS 6 Odin

### ISSUE THREAD

**Issue by smessina0076** [elementary/stylesheet#1074] opened 2021-08-13 13:21 UTC
## What Happened
I've installed and configured thunderbird 78.11.0 (64-bit). When I open an email and try to select text (with mouse or touchpad) I cannot see the selection 

## Expected Behavior
I expect to see the selected highlighted

## Steps to Reproduce

1. Install thunderbird trough apt: sudo apt install thunderbird
2. Configure an email account on thunderbird
3. Open/Read and email and try to select text

## Platform Information

LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Elementary
Description:	elementary OS 6 Odin
Release:	6
Codename:	odin

description: Notebook
product: 20FMS05K3R (LENOVO_MT_20FM_BU_Think_FM_ThinkPad T460)
vendor: LENOVO
version: ThinkPad T460
width: 64 bits
capabilities: smbios-2.8 dmi-2.8 smp vsyscall32

**Comment by cassidyjames** [comment] 2021-08-13 16:21
Duplicate of #805

This is a bug in the Firefox engine that we reported over a year ago and has been fixed for 11 months: https://bugzilla.mozilla.org/show_bug.cgi?id=1654323

Thunderbird appears to still be using an old version of that engine, and thus is incorrectly retrieving the selection color in its non-native toolkit. You can try the Flatpak from a third-party source like Flathub, but ultimately it is an issue that only Thunderbird can fix.

**Closed** 2021-08-13 16:21 UTC
