### ISSUE TITLE
Fullscreen Evince toolbar is transparent

### ISSUE THREAD

**Issue by Blast-City** [elementary/stylesheet#453] opened 2018-12-01 13:30 UTC
Hi.  

When Elementary default document viewer (Evince) is in fullscreen mode, the toolbar on the top only appears if you hover the mouse near the top of the screen. Unfortunately this tool bar is transparent which makes it harder to see the toolbar content.  

On Ubuntu the toolbar is opaque.

I think Elementary Evince design should be similar to Ubuntu.

Another thing that i noticed is the icons position on the fullscreen toolbar. They seem to be too close to left and right side of the screen. Maybe this happen because the toolbar is not opaque an you can't see the icon box outline, but I'm not sure.

P.S: Sorry if this is not the right place to talk about this issues.

**Comment by cassidyjames** [comment] 2019-10-05 20:44
Even though this predates it, marking this as a duplicate of #550 since it's more specific and on our radar now. Sorry for any confusion!

**Closed by cassidyjames** 2019-10-05 20:44 UTC
