### ISSUE TITLE
Active applications are not visible clearly on the default white dock

### ISSUE THREAD

**Issue by uncertainquark** [elementary/stylesheet#322] opened 2018-04-30 12:01 UTC
Active applications on a white dock:
![light](https://user-images.githubusercontent.com/22585732/37863521-3dff41e2-2f85-11e8-9821-19df8b16f81d.png)

Active applications on a dark dock:
![dark](https://user-images.githubusercontent.com/22585732/37863524-43e98b26-2f85-11e8-8a8b-d723a32ad900.png)

The difference is substantial and signals that visibility of the open apps need to be improved.

**Comment by danrabbit** [comment] 2020-01-03 06:20
Closing as a duplicate of #290

**Closed by danrabbit** 2020-01-03 06:20 UTC
