### ISSUE TITLE
Odin: Dark artifact around Firefox Downloads window

### ISSUE THREAD

**Issue by marbetschar** [elementary/stylesheet#893] opened 2020-12-02 17:02 UTC
## What Happened

The Downloads window in Firefox has a dark rectanglish artifact around it on Odin. But if I do a Screenshot, the artifact is not visible - therefore I had to fake the following picture. But it looks quite similar to what I see on my Dell XPS 13 7930. FWIW: I do not encounter any graphics issues apart from this:

![Screenshot from 2020-12-02 17-53-54](https://user-images.githubusercontent.com/392542/100905469-6656cc00-34c8-11eb-9801-b92ab28d6bca.png)

## Expected Behavior

The Downloads window should not have this extra rectangle. It should just be displayed on top of the browser window like any other window.

**Comment by mcclurgm** [comment] 2020-12-02 17:20
I believe this is a duplicate of elementary/gala#948. It's also present in Hera (I've been getting it for other Firefox windows).

**Closed** 2020-12-02 19:33 UTC
Labels: Status: Duplicate, Status: Out of Scope
