### ISSUE TITLE
Completely broken styles for some non-focused applications (like dconf-editor)

### ISSUE THREAD

**Issue by moqmar** [elementary/stylesheet#872] opened 2020-10-30 09:11 UTC
## What Happened
I was using `dconf-editor` and switched to another application. Now, `dconf-editor` looks horrible until I focus it again:

![grafik](https://user-images.githubusercontent.com/5559994/97681067-fb187500-1a97-11eb-8621-d80e125e61c1.png)

## Expected Behavior
The same styles as for all other non-focused windows.

## Steps to Reproduce
1. Open dconf-editor and another program
2. Focus the other program

### Logs
N/A

## Platform Information
- The version of elementary OS you are using: 6.0 Next
- The version of the software you are using: `apt show io.elementary.stylesheet` shows `5.9.9+r148+pkg330~daily~ubuntu6.0.1`
- Relevant hardware information such as graphics drivers, unconventional setups, etc.:
  - NVIDIA Driver

**Comment by danrabbit** [comment] 2020-11-03 22:07
This seems to be a duplicate of #734

**Closed by danrabbit** 2020-11-03 22:07 UTC
